version: "3.9"

services:
  xclip-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVICE: gpu
        BASE_IMAGE: nvidia/cuda:12.1.0-base-ubuntu20.04
    image: xclip-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${PWD}:/app
    command: ["python3", "main.py"]

  xclip-cpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVICE: cpu
        BASE_IMAGE: python:3.12-slim
    image: xclip-cpu
    volumes:
      - ${PWD}:/app
    command: ["python3", "main.py"]
